/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ClienteJpaController;
import Controle.PedidoJpaController;
import Controle.ProdutoJpaController;
import Modelo.Cliente;
import Modelo.Pedido;
import Modelo.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author euler
 */
public class Principal extends javax.swing.JFrame {

    String emf = "TrabalhoFinalGerenciaConfigPU";
    PedidoJpaController oPedidoJpaController = new PedidoJpaController(emf);
    ProdutoJpaController oProdutoJpaController = new ProdutoJpaController(emf);
    ClienteJpaController oClienteJpaController = new ClienteJpaController(emf);

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMProduto = new javax.swing.JMenu();
        jMIConsulta = new javax.swing.JMenuItem();
        jMIInclusao = new javax.swing.JMenuItem();
        jMIAlteracao = new javax.swing.JMenuItem();
        jMIExclusao = new javax.swing.JMenuItem();
        jMCliente = new javax.swing.JMenu();
        jMIConsulta1 = new javax.swing.JMenuItem();
        jMIInclusao1 = new javax.swing.JMenuItem();
        jMIAlteracao1 = new javax.swing.JMenuItem();
        jMIExclusao1 = new javax.swing.JMenuItem();
        jMPedido = new javax.swing.JMenu();
        jMIConsulta2 = new javax.swing.JMenuItem();
        jMIInclusao2 = new javax.swing.JMenuItem();
        jMIAlteracao2 = new javax.swing.JMenuItem();
        jMIExclusao2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMProduto.setText("Produto");

        jMIConsulta.setText("Consulta");
        jMIConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsultaActionPerformed(evt);
            }
        });
        jMProduto.add(jMIConsulta);

        jMIInclusao.setText("Inclusão");
        jMIInclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInclusaoActionPerformed(evt);
            }
        });
        jMProduto.add(jMIInclusao);

        jMIAlteracao.setText("Alteração");
        jMIAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlteracaoActionPerformed(evt);
            }
        });
        jMProduto.add(jMIAlteracao);

        jMIExclusao.setText("Exclusão");
        jMIExclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExclusaoActionPerformed(evt);
            }
        });
        jMProduto.add(jMIExclusao);

        jMenuBar1.add(jMProduto);

        jMCliente.setText("Cliente");

        jMIConsulta1.setText("Consulta");
        jMIConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsulta1ActionPerformed(evt);
            }
        });
        jMCliente.add(jMIConsulta1);

        jMIInclusao1.setText("Inclusão");
        jMIInclusao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInclusao1ActionPerformed(evt);
            }
        });
        jMCliente.add(jMIInclusao1);

        jMIAlteracao1.setText("Alteração");
        jMIAlteracao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlteracao1ActionPerformed(evt);
            }
        });
        jMCliente.add(jMIAlteracao1);

        jMIExclusao1.setText("Exclusão");
        jMIExclusao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExclusao1ActionPerformed(evt);
            }
        });
        jMCliente.add(jMIExclusao1);

        jMenuBar1.add(jMCliente);

        jMPedido.setText("Pedido");

        jMIConsulta2.setText("Consulta");
        jMIConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsulta2ActionPerformed(evt);
            }
        });
        jMPedido.add(jMIConsulta2);

        jMIInclusao2.setText("Inclusão");
        jMIInclusao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInclusao2ActionPerformed(evt);
            }
        });
        jMPedido.add(jMIInclusao2);

        jMIAlteracao2.setText("Alteração");
        jMIAlteracao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlteracao2ActionPerformed(evt);
            }
        });
        jMPedido.add(jMIAlteracao2);

        jMIExclusao2.setText("Exclusão");
        jMIExclusao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExclusao2ActionPerformed(evt);
            }
        });
        jMPedido.add(jMIExclusao2);

        jMenuBar1.add(jMPedido);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIInclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInclusaoActionPerformed
        Produto oProduto = new Produto();
        String descricao = JOptionPane.showInputDialog(null, "Informe o nome do Produto:");
        String fabricante = JOptionPane.showInputDialog(null, "Informe o nome do fabricante do Produto:");
        double valor = Double.parseDouble(JOptionPane.showInputDialog(null, "Informe o valor do fabricante do Produto:"));
        
        oProduto.setDescricao(descricao);
        oProduto.setFabricante(fabricante);
        oProduto.setValor(valor);
        
        oProdutoJpaController.create(oProduto);
        JOptionPane.showMessageDialog(null, "Sucesso ao Cadastrar!\n"
                + oProduto.toString());
    }//GEN-LAST:event_jMIInclusaoActionPerformed

    private void jMIConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsultaActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do seu produto para Consulta"));
        Produto oProduto = oProdutoJpaController.findProduto(id);
        if (oProduto != null) {
            JOptionPane.showMessageDialog(null, "Produto Encontrado!\n" + oProduto.toString());
        } else {
            JOptionPane.showMessageDialog(null, "Produto não consta na base de dados!");
        }


    }//GEN-LAST:event_jMIConsultaActionPerformed

    private void jMIAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlteracaoActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do seu produto para Alteração:"));
        Produto oProduto = oProdutoJpaController.findProduto(id);
        if (oProduto != null) {
            String descricao = JOptionPane.showInputDialog(null, "Insira a nova descrição:");
            String fabricante = JOptionPane.showInputDialog(null, "Insira o novo fabricante:");
            double valor = Double.parseDouble(JOptionPane.showInputDialog(null, " Insira o novo  valor:"));
            oProduto.setDescricao(descricao);
            oProduto.setFabricante(fabricante);
            oProduto.setValor(valor);
            try {
                oProdutoJpaController.edit(oProduto);
                JOptionPane.showMessageDialog(null, "Alteração feita com sucesso!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Produto não consta na base de dados!");
        }

    }//GEN-LAST:event_jMIAlteracaoActionPerformed

    private void jMIExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExclusaoActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do seu produto para Exclusão:"));
        Produto oProduto = oProdutoJpaController.findProduto(id);
        if (oProduto != null) {
            try {
                oProdutoJpaController.destroy(id);
                JOptionPane.showMessageDialog(null, "Produto Excluido!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Produto não consta na base de dados!");
        }


    }//GEN-LAST:event_jMIExclusaoActionPerformed

    private void jMIConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsulta1ActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do Cliente para Consulta"));
        Cliente oCliente = oClienteJpaController.findCliente(id);
        if (oCliente != null) {
            JOptionPane.showMessageDialog(null, "Cliente Encontrado!\n" + oCliente.toString());
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não consta na base de dados!");
        }
    }//GEN-LAST:event_jMIConsulta1ActionPerformed

    private void jMIInclusao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInclusao1ActionPerformed
        Cliente oCliente = new Cliente();
        String nome = JOptionPane.showInputDialog(null, "Insira o nome do Cliente");
        String cpf = JOptionPane.showInputDialog(null, "Insira o CPF do Cliente");
        String logradouro = JOptionPane.showInputDialog(null, "Insira o Logradouro do Cliente");
        String numero = JOptionPane.showInputDialog(null, "Insira o Número do Cliente");
        String bairro = JOptionPane.showInputDialog(null, "Insira o Bairro do Cliente");
        String cidade = JOptionPane.showInputDialog(null, "Insira a Cidade do Cliente");
        String estado = JOptionPane.showInputDialog(null, "Insira o Estado do Cliente");
        String cep = JOptionPane.showInputDialog(null, "Insira o CEP do Cliente");
        oCliente.setNome(nome);
        oCliente.setCPF(cpf);
        oCliente.setLogradouro(logradouro);
        oCliente.setNumero(numero);
        oCliente.setBairro(bairro);
        oCliente.setCidade(cidade);
        oCliente.setEstado(estado);
        oCliente.setCEP(cep);
        oClienteJpaController.create(oCliente);
        JOptionPane.showMessageDialog(null, "Cliente " + oCliente.getId() + " Cadastrado com sucesso!");
    }//GEN-LAST:event_jMIInclusao1ActionPerformed

    private void jMIAlteracao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlteracao1ActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do Cliente para Alterar"));
        Cliente oCliente = oClienteJpaController.findCliente(id);
        if (oCliente != null) {
            String nome = JOptionPane.showInputDialog(null, "Insira o novo nome do Cliente");
            String cpf = JOptionPane.showInputDialog(null, "Insira o novo CPF do Cliente");
            String logradouro = JOptionPane.showInputDialog(null, "Insira o novo Logradouro do Cliente");
            String numero = JOptionPane.showInputDialog(null, "Insira o novo Número do Cliente");
            String bairro = JOptionPane.showInputDialog(null, "Insira o novo Bairro do Cliente");
            String cidade = JOptionPane.showInputDialog(null, "Insira a nova Cidade do Cliente");
            String estado = JOptionPane.showInputDialog(null, "Insira o novo Estado do Cliente");
            String cep = JOptionPane.showInputDialog(null, "Insira o novo CEP do Cliente");

            oCliente.setNome(nome);
            oCliente.setCPF(cpf);
            oCliente.setLogradouro(logradouro);
            oCliente.setNumero(numero);
            oCliente.setBairro(bairro);
            oCliente.setCidade(cidade);
            oCliente.setEstado(estado);
            oCliente.setCEP(cep);

            try {
                oClienteJpaController.edit(oCliente);
                JOptionPane.showMessageDialog(null, "Cliente Alterado com Sucesso!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não consta na base de dados!");
        }

    }//GEN-LAST:event_jMIAlteracao1ActionPerformed

    private void jMIExclusao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExclusao1ActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do seu Cliente para Exclusão:"));
        Cliente oCliente = oClienteJpaController.findCliente(id);
        if (oCliente != null) {
            try {
                oClienteJpaController.destroy(id);
                JOptionPane.showMessageDialog(null, "Cliente Excluido!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não consta na base de dados!");
        }

    }//GEN-LAST:event_jMIExclusao1ActionPerformed

    private void jMIConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsulta2ActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do Pedido para Consulta"));
        Pedido oPedido = oPedidoJpaController.findPedido(id);
        if (oPedido != null) {
            JOptionPane.showMessageDialog(null, "Pedido Encontrado!\n" + oPedido.toString());
        } else {
            JOptionPane.showMessageDialog(null, "Pedido não consta na base de dados!");
        }
    }//GEN-LAST:event_jMIConsulta2ActionPerformed

    private void jMIInclusao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInclusao2ActionPerformed
        Pedido oPedido = new Pedido();
        Long idCliente = Long.parseLong(JOptionPane.showInputDialog(null, "Insisra o id do Cliente"));
        Cliente oCliente = oClienteJpaController.findCliente(idCliente);
        if (oCliente != null) {
            boolean quero = true;
            ArrayList<String> pedidos = new ArrayList<>();
            double valorTotal = 0;
            while (quero) {
                Long idProduto = Long.parseLong(JOptionPane.showInputDialog(null, "Insisra o id do Produto"));
                Produto oProduto = oProdutoJpaController.findProduto(idProduto);
                if (oProduto != null) {
                    int quantidade = Integer.parseInt(JOptionPane.showInputDialog(null, "Insisra a quantidade"));
                    double precoUnitario = Double.parseDouble(JOptionPane.showInputDialog(null, "Insisra o valor unitário"));
                    double desconto = Double.parseDouble(JOptionPane.showInputDialog(null, "Insisra o valor de desconto"));

                    String pedido = oProduto.getDescricao() + "    Qtd: " + quantidade + "    Desc.: " + desconto + "    Pre.Unt.: " + precoUnitario;
                    pedidos.add(pedido);
                    valorTotal = valorTotal + ((precoUnitario * quantidade) - desconto);
                } else {
                    JOptionPane.showMessageDialog(null, "Produto não consta na base de dados!");
                }

                String ver = JOptionPane.showInputDialog(null, "Deseja comprar outro Produto?"
                        + "\n(S) para continuar ou (N) para finalizar");
                if (ver.equalsIgnoreCase("n")) {
                    quero = false;
                }
            }
            oPedido.setIdCliente(idCliente);
            
            oPedido.setValorTotal(valorTotal);
            oPedidoJpaController.create(oPedido);
            JOptionPane.showMessageDialog(null, "Seu pedido:\n" + oPedido.toString());
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não consta na base de dados!");

        }

    }//GEN-LAST:event_jMIInclusao2ActionPerformed

    private void jMIAlteracao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlteracao2ActionPerformed
        Pedido oPedido = null;
            
            long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do Pedido para Consulta"));
            oPedido = oPedidoJpaController.findPedido(id);
            if (oPedido != null) {
                JOptionPane.showMessageDialog(null, "Pedido Encontrado!\n" + oPedido.toString());
                TelaPedido tp = new TelaPedido();
                tp.setVisible(true);
                tp.setaCampos(oPedido);
            } else {
                JOptionPane.showMessageDialog(null, "Pedido não consta na base de dados!");
            }
            
            
         
            

    }//GEN-LAST:event_jMIAlteracao2ActionPerformed

    private void jMIExclusao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExclusao2ActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(null, "Insira o id do Pedido para Exclusão"));
        Pedido oPedido = oPedidoJpaController.findPedido(id);
        if (oPedido != null) {
            try {
                oPedidoJpaController.destroy(id);
                JOptionPane.showMessageDialog(null, "Pedido excluido com sucesso!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pedido não consta na base de dados!");
        }
    }//GEN-LAST:event_jMIExclusao2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMCliente;
    private javax.swing.JMenuItem jMIAlteracao;
    private javax.swing.JMenuItem jMIAlteracao1;
    private javax.swing.JMenuItem jMIAlteracao2;
    private javax.swing.JMenuItem jMIConsulta;
    private javax.swing.JMenuItem jMIConsulta1;
    private javax.swing.JMenuItem jMIConsulta2;
    private javax.swing.JMenuItem jMIExclusao;
    private javax.swing.JMenuItem jMIExclusao1;
    private javax.swing.JMenuItem jMIExclusao2;
    private javax.swing.JMenuItem jMIInclusao;
    private javax.swing.JMenuItem jMIInclusao1;
    private javax.swing.JMenuItem jMIInclusao2;
    private javax.swing.JMenu jMPedido;
    private javax.swing.JMenu jMProduto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
